### PR TITLE
fix dxle::distance

### PR DESCRIPTION
**Pull request by akinomyoga**
I think a call of hypot is missing, which results in discarded y components.

### CODE REVIEW

**Comment by yumetodo** [comment]
Oh...

**Please add your name** to
https://github.com/Nagarei/DxLibEx/blob/master/AUTHORS

After that, I will marge.

**Comment by akinomyoga** [comment]
Oh, sorry. I added.

**Comment by yumetodo** [comment]
@akinomyoga Thank you.

**Comment by akinomyoga** [comment]
Thanks!

**Pull request merged**
