### PR TITLE
Fix is_castable

### PR DESCRIPTION
**Pull request by cppext**
is_castable should be either is_constructible or is_convertible

### CODE REVIEW

**Comment by yumetodo** [comment]
@cppext Thank you for your contributing! LGTM!

**Comment by yumetodo** [comment]
@cppext Could you add your name and e-mail to https://github.com/Nagarei/DxLibEx/blob/master/AUTHORS ?

**Comment by cppext** [comment]
@yumetodo  Thank you, but it's ok for me to be Nameless in AUTHOR for a slight fix.

**Comment by yumetodo** [comment]
@cppext OK. Thank you for your contribution. I'm surprised that there are people who want to contribute such a no longer maintained library!

Because this library was targeted to C++11 which is an old standard now, this repo was not maintained.

**Pull request merged**
